/* Action types */
export const FETCH_MATCHES = 'FETCH_MATCHES'
export const FETCH_ADDRESS = 'FETCH_ADDRESS'
export const FETCH_BETS = 'FETCH_BETS'
export const POST_BET_INFO = 'POST_BET_INFO'
export const POST_OPPOSING_BET_INFO = 'POST_OPPOSING_BET_INFO'
export const RESET_DESTINATION_TAG = 'RESET_DESTINATION_TAG'